const TG=window.Telegram?.WebApp;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const S={home:null,current:null,season:null,bot:'',user:null};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const api=(path,opt={})=>fetch(path,{cache:'no-store',headers:{'Content-Type':'application/json',...(opt.headers||{}),...(TG?.initData?{'X-Telegram-Init-Data':TG.initData}:{})},...opt}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Server xatosi');return d});
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function tgInit(){if(!TG)return;TG.ready();TG.expand();try{TG.setHeaderColor('#07080b');TG.setBackgroundColor('#07080b');TG.enableClosingConfirmation?.()}catch{}}
function page(n){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+n+'Page')?.classList.add('active');$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===n));scrollTo({top:0,behavior:'smooth'});if(n==='profile')loadProfile();if(n==='favorites')loadFavorites();if(n==='history')loadHistory();if(n==='pass')loadPass();if(n==='catalog')loadCatalog()}
function card(a){return `<article class="card" data-id="${a.id}"><div class="poster">${a.poster?`<img src="${esc(a.poster)}" loading="lazy" alt="${esc(a.title)}">`:'<div></div>'}<span class="rating">★ ${Number(a.rating||0).toFixed(2)}</span>${a.premium?'<span class="pass-tag">PASS</span>':''}</div><div class="card-title">${esc(a.title)}</div><div class="card-meta">${a.year||'—'} · ${esc((a.genres||'Anime').split(',')[0])}</div></article>`}
function render(el,items){if(!el)return;el.innerHTML=items?.length?items.map(card).join(''):'<div class="empty"><b>Hozircha hech narsa yo‘q</b>Bu bo‘limda ma’lumot topilmadi.</div>'}
function hero(a){const h=$('#hero');h.classList.remove('skeleton');if(!a){h.innerHTML='<div class="hero-copy"><small>O‘ZBEKCHA ANIME KATALOGI</small><h1>Sevimli anime.<br><em>Bir joyda.</em></h1><p>Anime qidiring, saqlang va tomoshani qolgan joyidan davom ettiring.</p></div>';return}const bg=a.banner||a.poster;h.innerHTML=`${bg?`<div class="hero-bg" style="background-image:url('${esc(bg)}')"></div>`:''}<div class="hero-copy"><small>O‘ZBEKCHA ANIME KATALOGI</small><h1>${esc(a.title)}<br><em>tomosha qilishga tayyor.</em></h1><p>${esc((a.description||'Sevimli animeingizni bir joyda boshqaring.').slice(0,190))}</p><div class="hero-actions"><button class="primary" data-open="${a.id}">Tomosha qilish</button><button class="secondary" data-page="catalog">Katalog</button></div></div>`}
async function loadHome(){try{S.home=await api('/api/home');const all=[...(S.home.popular||[]),...(S.home.newest||[])];hero(all[0]);render($('#popularRail'),S.home.popular);render($('#newRail'),S.home.newest);$('#homeGenres').innerHTML=(S.home.genres||[]).slice(0,16).map(g=>`<button class="genre" data-genre="${esc(g)}">${esc(g)}</button>`).join('');const h=await api('/api/history');if(h.items?.length){$('#continueSection').classList.remove('hidden');$('#continueRail').innerHTML=h.items.slice(0,10).map(x=>`<article class="card" data-episode="${x.episode_id}"><div class="poster"><div></div><span class="rating">▶ ${x.episode_number}-qism</span></div><div class="card-title">${esc(x.title)}</div><div class="card-meta">Davom ettirish</div></article>`).join('')}}catch(e){$('#offline').classList.remove('hidden');toast(e.message)}}
async function loadMeta(){try{const d=await api('/api/meta');S.bot=d.bot_username||''}catch{}}
async function search(q){q=String(q||'').trim();if(!q)return;page('search');$('#searchInput').value=q;$('#clearBtn').classList.remove('hidden');try{const d=await api('/api/search?q='+encodeURIComponent(q));$('#searchTitle').textContent=q;$('#resultCount').textContent=`${d.items.length} ta`;render($('#searchGrid'),d.items)}catch(e){toast(e.message)}}
async function loadCatalog(){if(!S.home)return;const gs=S.home.genres||[];$('#genreChips').innerHTML=`<button class="chip active" data-genre="__all">Barchasi</button>`+gs.map(g=>`<button class="chip" data-genre="${esc(g)}">${esc(g)}</button>`).join('');render($('#catalogGrid'),S.home.catalog||[])}
async function genre(g){$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.genre===g));if(g==='__all'){render($('#catalogGrid'),S.home?.catalog||[]);return}try{const d=await api('/api/search?q='+encodeURIComponent(g));render($('#catalogGrid'),d.items)}catch(e){toast(e.message)}}
async function openAnime(id){try{const d=await api('/api/anime/'+id);S.current=d;const a=d.anime;$('#detailTitle').textContent=a.title;$('#detailMeta').textContent=`★ ${Number(a.rating||0).toFixed(2)} · ${a.year||'—'} · ${a.status||'—'}\n${a.genres||'Janr ko‘rsatilmagan'}${a.studio?' · '+a.studio:''}`;$('#detailDesc').textContent=a.description||'Tavsif kiritilmagan.';$('#detailCover').innerHTML=a.banner?`<img src="${esc(a.banner)}">`:a.poster?`<img src="${esc(a.poster)}">`:'';$('#detailPoster').innerHTML=a.poster?`<img src="${esc(a.poster)}">`:'';const ss=d.seasons||[];$('#seasonTabs').innerHTML=ss.length?ss.map((s,i)=>`<button class="${i===0?'active':''}" data-season="${s.id}">${esc(s.title||s.number+'-fasl')}</button>`).join(''):'<span class="empty">Fasl kiritilmagan.</span>';renderEpisodes(ss[0]?.id);const r=await api('/api/anime/'+id+'/related').catch(()=>({items:[]}));render($('#relatedRail'),r.items||[]);openModal('detail')}catch(e){toast(e.message)}}
function renderEpisodes(sid){S.season=sid;const list=(S.current?.episodes||[]).filter(e=>Number(e.season_id)===Number(sid));$('#episodeList').innerHTML=list.length?list.map(e=>`<div class="episode"><div class="episode-num">${e.number}</div><div class="episode-copy"><b>${esc(e.title||e.number+'-qism')}</b><small>${e.premium?'✦ Premium':'Tomosha qilish'}</small></div><button class="episode-play ${e.premium?'lock':''}" data-episode="${e.id}">${e.premium?'✦':'▶'}</button></div>`).join(''):'<div class="empty"><b>Qismlar topilmadi</b>Bu faslga hali qism qo‘shilmagan.</div>'}
async function openEpisode(id){try{const d=await api('/api/episode/'+id);$('#playerTitle').textContent=d.title||`${d.number}-qism`;if(d.media_url)$('#playerBox').innerHTML=`<div>Media tayyor.<br><a href="${esc(d.media_url)}" target="_blank" rel="noopener">Tomosha qilish →</a></div>`;else if(d.file_id&&d.bot_url)$('#playerBox').innerHTML=`<div>Qism Telegram fayli sifatida saqlangan.<br><a href="${esc(d.bot_url)}">Telegramda ochish →</a></div>`;else $('#playerBox').innerHTML='<div>Bu qism uchun media hali ulanmagan.</div>';openModal('player')}catch(e){toast(e.message)}}
function openModal(n){$('#'+n+'Modal').classList.add('show');$('#'+n+'Modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(n){$('#'+n+'Modal').classList.remove('show');$('#'+n+'Modal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function toggleFavorite(){if(!S.current?.anime?.id)return;try{const d=await api('/api/favorite',{method:'POST',body:JSON.stringify({anime_id:S.current.anime.id})});toast(d.added?'❤️ Sevimliga qo‘shildi':'💔 Sevimlilardan olindi')}catch(e){toast(e.message)}}
async function loadFavorites(){try{const d=await api('/api/favorites');render($('#favoritesGrid'),d.items)}catch(e){toast(e.message)}}
async function loadHistory(){try{const d=await api('/api/history');$('#historyList').innerHTML=d.items?.length?d.items.map(x=>`<div class="history-item"><div class="history-thumb"></div><div class="history-copy"><b>${esc(x.title)}</b><small>${x.episode_number}-qism · Davom ettirish</small></div><button data-episode="${x.episode_id}">▶</button></div>`).join(''):'<div class="empty"><b>Tarix bo‘sh</b>Anime tomosha qilsangiz shu yerda chiqadi.</div>'}catch(e){toast(e.message)}}
async function loadProfile(){try{const d=await api('/api/profile');S.user=d.user||{};const u=S.user,av=(u.first_name||'A').slice(0,1).toUpperCase();$('#topAvatar').textContent=av;$('#profileCard').innerHTML=`<div class="profile-cover"></div><div class="profile-main"><div class="profile-avatar">${esc(av)}</div><div><h2>${esc(u.first_name||'Mehmon')}</h2><p>${u.username?'@'+esc(u.username):'@guest'}</p></div></div><div class="profile-stats"><div><b>${u.total_watched||0}</b><span>KO‘RILGAN</span></div><div><b>${u.favorites||0}</b><span>SEVIMLI</span></div><div><b>${u.referrals||0}</b><span>TAKLIF</span></div></div>`;if(u.is_admin&&!$('#adminPage').classList.contains('active')){$('#profileCard').insertAdjacentHTML('afterend','<button id="adminLink" class="admin-link">⚙️ Admin boshqaruvi →</button>');$('#adminLink').onclick=()=>{page('admin');loadAdmin()}}}catch(e){toast(e.message)}}
async function loadPass(){try{const d=await api('/api/pass');$('#passStatus').textContent=d.active?'✓ Pass faol':'Pass faol emas';$('#plans').innerHTML=(d.plans||[]).map((p,i)=>`<article class="plan ${i===2?'highlight':''}"><label>${i===2?'OMMABOP':'PASS'}</label><h3>${esc(p.title)}</h3><small>⭐ ${p.stars} Telegram Stars</small><button data-plan="${p.days}">Sotib olish</button></article>`).join('')}catch(e){toast(e.message)}}
async function loadAdmin(){try{const d=await api('/api/admin/stats');$('#adminStats').innerHTML=[['Users',d.users],['Anime',d.anime],['Episodes',d.episodes],['Views',d.views],['Pass',d.active_pass],['Favorites',d.favorites]].map(x=>`<div class="stat"><b>${x[1]??0}</b><small>${x[0]}</small></div>`).join('')}catch(e){toast(e.message)}}
function shareAnime(){const a=S.current?.anime;if(!a)return;const url=S.bot?`https://t.me/${S.bot}?start=anime_${a.id}`:'';if(TG?.openTelegramLink&&url){TG.openTelegramLink(`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(a.title)}`);return}navigator.clipboard?.writeText(url||a.title);toast('Ulashish havolasi nusxalandi')}
function bind(){document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){page(p.dataset.page);return}const c=e.target.closest('[data-open]');if(c){openAnime(Number(c.dataset.open));return}const pc=e.target.closest('.card[data-id]');if(pc){openAnime(Number(pc.dataset.id));return}const ep=e.target.closest('[data-episode]');if(ep){openEpisode(Number(ep.dataset.episode));return}const s=e.target.closest('[data-season]');if(s){$$('.season-tabs button').forEach(x=>x.classList.remove('active'));s.classList.add('active');renderEpisodes(Number(s.dataset.season));return}const cl=e.target.closest('[data-close]');if(cl){closeModal(cl.dataset.close);return}const g=e.target.closest('[data-genre]');if(g){if($('#catalogPage').classList.contains('active'))genre(g.dataset.genre);else{page('catalog');setTimeout(()=>genre(g.dataset.genre),0)}return}const pl=e.target.closest('[data-plan]');if(pl){const days=Number(pl.dataset.plan);const url=S.bot?`https://t.me/${S.bot}?start=buy_${days}`:'';if(TG?.openTelegramLink&&url)TG.openTelegramLink(url);else if(url)location.href=url;else toast('Bot username sozlanmagan');return}});$('#searchBtn').onclick=()=>search($('#searchInput').value);$('#searchInput').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};$('#searchInput').oninput=e=>$('#clearBtn').classList.toggle('hidden',!e.target.value);$('#clearBtn').onclick=()=>{$('#searchInput').value='';$('#clearBtn').classList.add('hidden')};$('#profileBtn').onclick=()=>page('profile');$('#favDetail').onclick=toggleFavorite;$('#shareDetail').onclick=shareAnime;$('#shareProfile').onclick=()=>{const url=S.bot?`https://t.me/${S.bot}`:'';if(TG?.openTelegramLink&&url)TG.openTelegramLink(url);else if(url)navigator.clipboard?.writeText(url);toast('Bot havolasi nusxalandi')};$('#grantPassBtn').onclick=async()=>{const id=prompt('Telegram user ID:');if(!id)return;const days=prompt('Necha kun?','30');if(!days)return;try{await api('/api/admin/grant-pass',{method:'POST',body:JSON.stringify({user_id:Number(id),days:Number(days)})});toast('Pass berildi');loadAdmin()}catch(e){toast(e.message)}};$('#openBotAdmin').onclick=()=>{if(S.bot){TG?.openTelegramLink?.(`https://t.me/${S.bot}`)}else toast('Bot username topilmadi')}}}
(async()=>{tgInit();bind();await loadMeta();await loadHome();await loadProfile()})()
